name: Deploy to Development Environment

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development

# Default configurations if not provided in secrets
env:
  DEFAULT_PORT: 3000         # Default internal port the app listens on

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint || echo "No lint command configured - skipping"
        continue-on-error: true
        
      - name: Run tests
        run: npm test
        
      - name: Create test results directory
        run: mkdir -p test-results coverage
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            coverage/
        if: always()
        continue-on-error: true

  build-and-push:
    name: Build and Push Docker Image
    needs: lint-and-test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}:dev-${{ github.sha }}
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}:development
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=development
          
  deploy-to-development:
    name: Deploy to Development Environment
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            # Set variables
            APP_NAME="${{ secrets.APP_NAME }}"
            CONTAINER_NAME="${APP_NAME}-dev"
            IMAGE_NAME="docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${APP_NAME}:dev-${{ github.sha }}"
            
            # Set deployment directory
            DEPLOY_PATH="/opt/deployment/${APP_NAME}-dev"
            
            sudo mkdir -p $DEPLOY_PATH
            cd $DEPLOY_PATH
            
            # Create directories for persistent data if they don't exist
            sudo mkdir -p $DEPLOY_PATH/data
            sudo mkdir -p $DEPLOY_PATH/logs
            
            # Pull the latest image
            sudo docker pull ${IMAGE_NAME}
            
            # Stop and remove any existing container with the same name
            sudo docker stop ${CONTAINER_NAME} || true
            sudo docker rm ${CONTAINER_NAME} || true
            
            # Run the new container with docker run
            echo "Starting new container..."
            sudo docker run -d \
              --name ${CONTAINER_NAME} \
              --restart unless-stopped \
              -p ${{ secrets.PORT }}:${{ env.DEFAULT_PORT }} \
              -e NODE_ENV=development \
              -e VIRTUAL_HOST=${{ secrets.DOMAIN }} \
              -e VIRTUAL_PORT=${{ env.DEFAULT_PORT }} \
              -e LETSENCRYPT_HOST=${{ secrets.DOMAIN }} \
              -e LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }} \
              -v $DEPLOY_PATH/data:/app/data \
              -v $DEPLOY_PATH/logs:/app/logs \
              --network ${{ secrets.DOCKER_NETWORK }} \
              ${IMAGE_NAME}
            
            # Clean up old images to save space (keep last 5)
            sudo docker image prune -a --filter "label=name=${APP_NAME}" --filter "until=240h" --force
          
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            # Set variables
            APP_NAME="${{ secrets.APP_NAME }}"
            CONTAINER_NAME="${APP_NAME}-dev"
            
            # Wait for the container to be ready
            sleep 15
            
            # Check if the container is running
            if sudo docker ps | grep ${CONTAINER_NAME}; then
              echo "Container is running"
              
              # Perform a basic health check
              # First check using local connection on the server
              if curl -s http://localhost:${{ env.DEFAULT_PORT }} | grep -q "Hello"; then
                echo "Local health check passed"
              else
                echo "Warning: Local health check did not detect expected content"
              fi
              
              # Then check using the domain (this might not work immediately due to DNS propagation)
              echo "Attempting domain health check (may not work immediately due to DNS propagation)"
              if curl -s https://${{ secrets.DOMAIN }} -k | grep -q "Hello"; then
                echo "Domain health check passed"
              else
                echo "Warning: Domain health check did not detect expected content"
                echo "This might be normal if DNS hasn't propagated or SSL certificate isn't ready yet"
              fi
            else
              echo "Container is not running"
              sudo docker logs ${CONTAINER_NAME}
              exit 1
            fi
            
      - name: Post deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment to development was successful!"
            echo "App is now available at https://${{ secrets.DOMAIN }}"
            echo "Deployment path on server: ${{ secrets.DEPLOY_PATH }}"
          else
            echo "❌ Deployment to development failed."
          fi